env: "local" # local, dev, prod

app:
  name: "passfort"
  version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  allow_origins: "*" # Example: 127.0.0.1, example.com

token:
  access_token_ttl: 30m
  refresh_token_ttl: 720h

master_password:
  master_password_ttl: 60m

clients:
  mail:
    timeout: 10s
    retries_count: 3
    insecure: false

log:
  slog:
    add_source: true
    level: "debug"
    format: "pretty"
    pretty:
      fields_format: "json"
      emoji: true
      # time_layout: "15:04:05.000000"
