env: "local" # local, dev, prod

app:
  name: "passfort"
  version: "1.0.0"

http:
  host: "0.0.0.0"
  port: 8080
  allow_origins: "*" # Example: 127.0.0.1, example.com

database:
  connection: "postgres"
  host: "localhost"
  port: 5432
  user: "user"
  name: "passfort"

cache:
  address: "localhost:6379"

token:
  access_token_ttl: 30m
  refresh_token_ttl: 720h

clients:
  mail:
    address: "localhost:44350"
    timeout: 10s
    retries_count: 3
    insecure: false

log:
  slog:
    add_source: true
    level: "debug"
    format: "pretty"
    pretty:
      fields_format: "json"
      emoji: true
      # time_layout: "15:04:05.000000"
